version: "3.9"

services:
  postgres:
    container_name: cc-postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      - local
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: on-failure
  redis:
    container_name: cc-redis
    image: redis:latest
    ports:
      - "6380:6379"
    networks:
      - local
    volumes:
      - redis-data:/var/lib/redis
    restart: on-failure
  prometheus:
    container_name: cc-prometheus
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - local
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/web.yml
    restart: on-failure
  postgres-exporter:
    container_name: cc-postgres-exporter
    image: prometheuscommunity/postgres-exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable"
    depends_on:
      - postgres
      - prometheus
    networks:
      - local
    restart: on-failure
  app:
    container_name: cc
    build: .
    depends_on:
      - postgres
      - redis
    ports:
      - "8081:8080"
    networks:
      - local
    env_file:
      - .env
    restart: on-failure

volumes:
  postgres-data:
  redis-data:
  prometheus-data:

networks:
  local:
    driver: bridge